name: Rancher Documentation
description: Documentation for Rancher


URL: "rancher.github.io"
baseurl: "http://superseb.github.io/"

exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from
